
const dummyData = [
    { id: 1, title: 'The Great Gatsby', author: 'F. Scott Fitzgerald', category: 'Classic' },
    { id: 2, title: 'To Kill a Mockingbird', author: 'Harper Lee', category: 'Classic' },
    { id: 3, title: '1984', author: 'George Orwell', category: 'Dystopian' },
    { id: 4, title: 'Brave New World', author: 'Aldous Huxley', category: 'Dystopian' },
    { id: 5, title: 'The Hitchhiker\'s Guide to the Galaxy', author: 'Douglas Adams', category: 'Science Fiction' },
    { id: 6, title: 'Dune', author: 'Frank Herbert', category: 'Science Fiction' },
    { id: 7, title: 'The Catcher in the Rye', author: 'J.D. Salinger', category: 'Coming-of-age' },
    { id: 8, title: 'Lord of the Flies', author: 'William Golding', category: 'Adventure' },
    { id: 9, title: 'The Hobbit', author: 'J.R.R. Tolkien', category: 'Fantasy' },
    { id: 10, title: 'Harry Potter and the Sorcerer\'s Stone', author: 'J.K. Rowling', category: 'Fantasy' },
    { id: 11, title: 'The Fellowship of the Ring', author: 'J.R.R. Tolkien', category: 'Fantasy' },
    { id: 12, title: 'The Two Towers', author: 'J.R.R. Tolkien', category: 'Fantasy' },
    { id: 13, title: 'The Return of the King', author: 'J.R.R. Tolkien', category: 'Fantasy' },
    { id: 14, title: 'Pride and Prejudice', author: 'Jane Austen', category: 'Romance' },
    { id: 15, title: 'Sense and Sensibility', author: 'Jane Austen', category: 'Romance' },
    { id: 16, title: 'Emma', author: 'Jane Austen', category: 'Romance' },
    { id: 17, title: 'Moby-Dick', author: 'Herman Melville', category: 'Adventure' },
    { id: 18, title: 'The Adventures of Tom Sawyer', author: 'Mark Twain', category: 'Adventure' },
    { id: 19, title: 'The War of the Worlds', author: 'H.G. Wells', category: 'Science Fiction' },
    { id: 20, title: 'The Call of Cthulhu', author: 'H.P. Lovecraft', category: 'Horror' },
    { id: 21, title: 'Dracula', author: 'Bram Stoker', category: 'Horror' },
    { id: 22, title: 'The Shining', author: 'Stephen King', category: 'Horror' },
    { id: 23, title: 'The Picture of Dorian Gray', author: 'Oscar Wilde', category: 'Gothic' },
    { id: 24, title: 'Frankenstein', author: 'Mary Shelley', category: 'Gothic' },
    { id: 25, title: 'The Scarlet Letter', author: 'Nathaniel Hawthorne', category: 'Historical Fiction' },
    { id: 26, title: 'Les Misérables', author: 'Victor Hugo', category: 'Historical Fiction' },
    { id: 27, title: 'The Count of Monte Cristo', author: 'Alexandre Dumas', category: 'Adventure' },
    { id: 28, title: 'Crime and Punishment', author: 'Fyodor Dostoevsky', category: 'Philosophical' },
    { id: 29, title: 'The Brothers Karamazov', author: 'Fyodor Dostoevsky', category: 'Philosophical' },
    { id: 30, title: 'One Hundred Years of Solitude', author: 'Gabriel García Márquez', category: 'Magical Realism' },
    { id: 31, title: 'Don Quixote', author: 'Miguel de Cervantes', category: 'Satire' },
    { id: 32, title: 'Anna Karenina', author: 'Leo Tolstoy', category: 'Romance' },
    { id: 33, title: 'The Divine Comedy', author: 'Dante Alighieri', category: 'Epic' },
    { id: 34, title: 'War and Peace', author: 'Leo Tolstoy', category: 'Historical Fiction' },
    { id: 35, title: 'The Iliad', author: 'Homer', category: 'Epic' },
    { id: 36, title: 'The Odyssey', author: 'Homer', category: 'Epic' },
    { id: 37, title: 'The Aeneid', author: 'Virgil', category: 'Epic' },
    { id: 38, title: 'The Grapes of Wrath', author: 'John Steinbeck', category: 'Social Realism' },
    { id: 39, title: 'East of Eden', author: 'John Steinbeck', category: 'Historical Fiction' },
    { id: 40, title: 'The Old Man and the Sea', author: 'Ernest Hemingway', category: 'Adventure' },
    { id: 41, title: 'The Da Vinci Code', author: 'Dan Brown', category: 'Mystery' },
    { id: 42, title: 'Gone Girl', author: 'Gillian Flynn', category: 'Mystery' },
    { id: 43, title: 'The Girl with the Dragon Tattoo', author: 'Stieg Larsson', category: 'Thriller' },
    { id: 44, title: 'The Silence of the Lambs', author: 'Thomas Harris', category: 'Thriller' },
    { id: 45, title: 'The Fault in Our Stars', author: 'John Green', category: 'Young Adult' },
    { id: 46, title: 'The Hunger Games', author: 'Suzanne Collins', category: 'Young Adult' },
    { id: 47, title: 'The Road', author: 'Cormac McCarthy', category: 'Post-Apocalyptic' },
    { id: 48, title: 'The Book Thief', author: 'Markus Zusak', category: 'Historical Fiction' },
    { id: 49, title: 'One Hundred Years of Solitude', author: 'Gabriel García Márquez', category: 'Magical Realism' },
    { id: 50, title: 'The Alchemist', author: 'Paulo Coelho', category: 'Philosophical' },
  ];
  
  export default dummyData;
  